
DROP TABLE IF EXISTS maintenance_logs   CASCADE;
DROP TABLE IF EXISTS restocking_events  CASCADE;
DROP TABLE IF EXISTS transactions       CASCADE;
DROP TABLE IF EXISTS machine_slots      CASCADE;
DROP TABLE IF EXISTS vending_machines   CASCADE;
DROP TABLE IF EXISTS products           CASCADE;
DROP TABLE IF EXISTS payment_methods    CASCADE;
DROP TABLE IF EXISTS employees          CASCADE;
DROP TABLE IF EXISTS suppliers          CASCADE;
DROP TABLE IF EXISTS locations          CASCADE;

--Справочные таблицы (без внешних ключей)

CREATE TABLE locations (
    location_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    address       VARCHAR(255) NOT NULL,
    city          VARCHAR(100) NOT NULL,
    location_type VARCHAR(50)
);

CREATE TABLE suppliers (
    supplier_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    contact_phone VARCHAR(30),
    contact_email VARCHAR(100)
);

CREATE TABLE payment_methods (
    payment_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name       VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(100) NOT NULL,
    role        VARCHAR(50),
    phone       VARCHAR(30),
    hired_date  DATE
);

--Таблицы первого уровня зависимости

CREATE TABLE products (
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    volume_ml   INT CHECK (volume_ml > 0),
    price       DECIMAL(10,2) NOT NULL CHECK (price >= 0),
    supplier_id BIGINT NOT NULL REFERENCES suppliers (supplier_id)
);

CREATE TABLE vending_machines (
    machine_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id    BIGINT NOT NULL REFERENCES locations (location_id),
    serial_number  VARCHAR(50) NOT NULL UNIQUE,
    model          VARCHAR(100),
    installed_date DATE,
    status         VARCHAR(30) NOT NULL DEFAULT 'active'
);

--Таблицы второго уровня

CREATE TABLE machine_slots (
    slot_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id       BIGINT NOT NULL REFERENCES vending_machines (machine_id),
    product_id       BIGINT NOT NULL REFERENCES products (product_id),
    slot_number      VARCHAR(10) NOT NULL,
    current_quantity INT NOT NULL DEFAULT 0 CHECK (current_quantity >= 0),
    max_capacity     INT NOT NULL CHECK (max_capacity > 0),
    UNIQUE (machine_id, slot_number),
    CHECK (current_quantity <= max_capacity)
);

CREATE TABLE maintenance_logs (
    maintenance_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id        BIGINT NOT NULL REFERENCES vending_machines (machine_id),
    employee_id       BIGINT NOT NULL REFERENCES employees (employee_id),
    issue_description TEXT,
    status            VARCHAR(30) NOT NULL DEFAULT 'open',
    reported_date     TIMESTAMP NOT NULL,
    resolved_date     TIMESTAMP
);

--Таблицы третьего уровня

CREATE TABLE transactions (
    transaction_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id        BIGINT NOT NULL REFERENCES vending_machines (machine_id),
    slot_id           BIGINT NOT NULL REFERENCES machine_slots (slot_id),
    payment_method_id BIGINT NOT NULL REFERENCES payment_methods (payment_method_id),
    amount            DECIMAL(10,2) NOT NULL CHECK (amount >= 0),
    transaction_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status            VARCHAR(30) NOT NULL DEFAULT 'success'
);

CREATE TABLE restocking_events (
    restock_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id        BIGINT NOT NULL REFERENCES machine_slots (slot_id),
    employee_id    BIGINT NOT NULL REFERENCES employees (employee_id),
    quantity_added INT NOT NULL CHECK (quantity_added > 0),
    restock_date   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);